@startuml
'https://plantuml.com/sequence-diagram

autonumber
actor User
participant SessionController << (C,#ADD1B2) Controller >>
participant SessionService << (C,#ADD1B2) Service >>
participant SessionRepository << (C,#ADD1B2) Repository >>
database H2

==Open==

User -> SessionController: PUT: /race/{id}/sessions/{session_stage}/open
activate SessionController
SessionController -> SessionService: OpenSession
activate SessionService
SessionService -> SessionRepository: FindSessionByRaceIdAndStage
activate SessionRepository
SessionRepository -> H2: SELECT...
H2 -> SessionRepository: session
SessionRepository -> SessionService: session
deactivate SessionRepository
SessionService -> SessionService: ValidateStatus
SessionService -> SessionService: ChangeSessionStatus
SessionService -> SessionRepository: Save
activate SessionRepository
SessionRepository -> H2: UPDATE...
H2 -> SessionRepository: session
SessionRepository -> SessionService: session saved
deactivate SessionRepository
SessionService -> SessionController: session
deactivate SessionService
SessionController -> User: Response
deactivate SessionController

==Close==

User -> SessionController: PUT: /race/{id}/sessions/{session_stage}/close
activate SessionController
SessionController -> SessionService: CloseSession
activate SessionService
SessionService -> SessionRepository: FindSessionByRaceIdAndStage
activate SessionRepository
SessionRepository -> H2: SELECT...
H2 -> SessionRepository: session
SessionRepository -> SessionService: session
deactivate SessionRepository
SessionService -> SessionService: ValidateStatus
SessionService -> SessionService: ChangeSessionStatus
SessionService -> SessionRepository: Save
activate SessionRepository
SessionRepository -> H2: UPDATE...
H2 -> SessionRepository: session
SessionRepository -> SessionService: session saved
deactivate SessionRepository
SessionService -> SessionController: session
deactivate SessionService
SessionController -> User: Response
deactivate SessionController

@enduml