version: '3'
services:
  user-service:
    container_name: user_service_app
    image: tup-user-service-app:1.0.0
    build: .
    ports:
      - 8083:8083
    depends_on:
      - java-db

  java-db:
    container_name: java-db
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
