server:
  port: 8079

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
        routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/products/**
          filters:
            - name: CircuitBreaker
              args:
                name: productCircuitBreaker
                fallbackUri: forward:/fallback/product
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders/**
          filters:
              - name: CircuitBreaker
                args:
                  name: orderCircuitBreaker
                  fallbackUri: forward:/fallback/order
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
          filters:
          - name: CircuitBreaker
            args:
              name: orderCircuitBreaker
              fallbackUri: forward:/fallback/user
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10000
        permitted-number-of-calls-in-half-open-state: 3