version: "3"

services:
  loteria-micro:
    image: finaloteria
    ports:
      - 8081:8081
    environment:
      APP_NAME: tomi

  loteria:
    image: gabrielarriola/api-loteria:latest
    ports:
      - 8082:8082